default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_webhook_secret: <%= ENV['STRIPE_WEBHOOK_SECRET'] %>
  twitter_consumer_key:  <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  twitter_oauth_token: <%= ENV['TWITTER_OAUTH_TOKEN'] %>
  twitter_oauth_token_secret: <%= ENV['TWITTER_OAUTH_SECRET'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
